# Generated by Django 3.1.8 on 2022-08-24 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessages',
            options={'verbose_name_plural': 'Chats'},
        ),
        migrations.AlterModelOptions(
            name='returns',
            options={'verbose_name_plural': 'Return'},
        ),
    ]
