# Generated by Django 3.1.8 on 2022-08-24 10:38

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('lib', '0002_auto_20220824_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Type')),
                ('notifiable_id', models.PositiveIntegerField(db_index=True, verbose_name='Notifiable Id')),
                ('data', jsonfield.fields.JSONField(verbose_name='Data')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('notifiable_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Notifiable Type')),
            ],
            options={
                'verbose_name_plural': 'Notification ',
            },
        ),
    ]
