# Generated by Django 3.1.8 on 2022-08-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0003_auto_20220806_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='date_created',
            new_name='date_requested',
        ),
        migrations.RemoveField(
            model_name='request',
            name='address',
        ),
        migrations.RemoveField(
            model_name='request',
            name='email',
        ),
        migrations.RemoveField(
            model_name='request',
            name='mobile',
        ),
        migrations.AddField(
            model_name='request',
            name='return_date',
            field=models.DateTimeField(null=True),
        ),
    ]
