# Generated by Django 3.1.8 on 2022-08-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0003_databasenotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatabaseNotification',
        ),
    ]
