# Generated by Django 3.1.8 on 2022-08-25 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0007_auto_20220825_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='book_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lib.request'),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='issue_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lib.request'),
        ),
        migrations.AlterField(
            model_name='request',
            name='return_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
