# Generated by Django 4.0.6 on 2022-08-09 04:01

from django.db import migrations, models
import django.db.models.deletion
import tkinter.tix


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0007_alter_area_id_alter_books_id_alter_chatmessages_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='Issuing_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lib.request'),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=tkinter.tix.Tree),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='status',
            field=models.CharField(choices=[('1', 'Available'), ('2', 'Unavailable')], default=1, max_length=2, null=True),
        ),
    ]
