# Generated by Django 3.1.8 on 2022-08-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0009_auto_20220818_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='return_date',
            field=models.DateTimeField(null=True),
        ),
    ]
