# Generated by Django 3.1.8 on 2022-08-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0011_returns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
